### 
POST {{local}}/getLatestOrders
content-type: application/json

{
"clientPublicKey": "...", 
"timestamp": "...",
"nonce": 0,
"signature": "..."
}
### 
POST {{local}}/getLatestTickers
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...",
"nonce": 1, 
"signature": "..."
}
### 
POST {{local}}/getLatestBalances
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...",
"nonce", 2, 
"signature": "..."
}
